language: cpp
compiler: 
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -q
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
script: 
  - cmake . 
  - make 
  - ./BundleAgent_test
