language: cpp
compiler: 
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -q
  - sudo apt-get install g++-4.8 -y
script: 
  - cmake . 
  - make 
  - ./BundleAgent_test
